name: tag

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: _cache
        key: ${{ runner.os }}-pip-${{ github.sha }}
        restore-keys: ${{ runner.os }}-pip-
    - name: versioning
      run: "echo \"VERSION = '${GITHUB_REF##*/v}'\" > sftpovw/version.py"
    - uses: wtnb75/actions/python@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
      with:
        pipinstall: "-r requirements.txt -r requirements-dev.txt"
    - uses: wtnb75/actions/ruff@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
    - uses: wtnb75/actions/pytest@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
      with:
        benchmark: "true"
    - id: wheel
      uses: wtnb75/actions/wheel@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
    - id: pdoc
      uses: wtnb75/actions/pdoc@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
      with:
        output-dir: docs
        module: sftpovw
    - uses: wtnb75/actions/pypi-upload@c1711251ea69e3e6d68db7a9fa019d79b497f70c # v1.0.3
      with:
        username: ${{ secrets.TWINE_USERNAME }}
        password: ${{ secrets.TWINE_PASSWORD }}
        file: dist/${{ steps.wheel.outputs.filename }}
